all: main

main: Drawable.hpp Option.hpp Menu.hpp Classifica.hpp TetrisBoard.hpp Game.hpp Tetramino.hpp utils.hpp Hud.hpp
	g++ -std=c++11 -lncurses -o main main.cpp Drawable.cpp Option.cpp Menu.cpp Classifica.cpp TetrisBoard.cpp Game.cpp Tetramino.cpp Hud.cpp
