all: main

main: Tetris.hpp Classifica.hpp  Menu.hpp Window.hpp
	g++ MainMenu.cpp src/Menu/Menu.cpp Tetris.cpp src/Window/Window.cpp src/Tetramino/Tetramino.cpp src/Classifica/Classifica.cpp -lncurses -o main
