all: main

main: Tetris.hpp Classifica.hpp Board.hpp Menu.hpp Window.hpp Option.hpp ../Tetramini/Tetramino.hpp
	g++ main.cpp Tetris.cpp Classifica.cpp Board.cpp Menu.cpp Window.cpp Option.cpp ../Tetramini/Tetramino.cpp -lncurses -o main
